modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "aurorion_core"
type = "required"
versionRange = "[0.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "aurorion_profissoes.mixins.json"

[[mixins]]
config = "aurorion_profissoes.lso.mixins.json"
requiredMods = ["legendarysurvivaloverhaul"]

[[mixins]]
config = "aurorion_profissoes.quality.mixins.json"
requiredMods = ["quality_food"]

[[mixins]]
config = "aurorion_profissoes.spoil.mixins.json"
requiredMods = ["foodspoil"]
