modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "aurorion_core"
type = "required"
versionRange = "[0.6.2,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "puffish_skills"
type = "required"
versionRange = "[0.19.0,0.20.0)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "aurorion_ethereal"
type = "optional"
versionRange = "[0.3.3,)"
ordering = "AFTER"
side = "BOTH"
